function getSavedLanguage(){try{const saved=localStorage.getItem('pawtion-language');return ['th','en'].includes(saved)?saved:'th';}catch{return'th';}}
const state = { species: 'dog', neutered: 'yes', bcs: 5, mcs: 'normal', step: 1, lang: getSavedLanguage(), theme: 'auto' };
const dictionary = {
  th: {
    navHome:'หน้าหลัก',navReferences:'แหล่งอ้างอิง',navCalc:'คำนวณอาหาร', heroEyebrow:'NUTRITION, SIMPLIFIED', heroTitle:'อาหารที่พอดี<br /><em>สำหรับเขา</em>', heroCopy:'คำแนะนำปริมาณอาหารรายวันสำหรับน้องหมา และ น้องแมว<br class="desktop" /> เริ่มจากข้อมูลเฉพาะตัวของน้องๆ', heroButton:'เริ่มคำนวณ <span>↓</span>',
    age:'อายุ',ageUnit:'หน่วยอายุ',weeks:'สัปดาห์',months:'เดือน',years:'ปี',days:'วัน',stepProgress:(step)=>`ขั้นตอน ${step} จาก 4`,adultSize:'ขนาดเมื่อโตเต็มวัย',sizeAuto:'ประเมินจากน้ำหนักปัจจุบัน',sizeSmall:'เล็ก — ต่ำกว่า 10 กก.',sizeMedium:'กลาง — 10–25 กก.',sizeLarge:'ใหญ่ — 25–40 กก.',sizeGiant:'ใหญ่มาก — มากกว่า 40 กก.',sizeHelp:'หากเลือกประเมินอัตโนมัติ Pawtion จะใช้น้ำหนักปัจจุบันเป็นค่าประมาณ',lifeStageTooltip:'ช่วงวัยช่วยให้ Pawtion เลือกแนวทางการคำนวณโภชนาการที่เหมาะสม แต่อายุเพียงอย่างเดียวไม่สามารถกำหนดความต้องการพลังงานได้ทั้งหมด โดยยังต้องพิจารณารูปร่าง ระดับกิจกรรม สถานะการทำหมัน การเจริญเติบโต สุขภาพ และความแตกต่างของสัตว์แต่ละตัวร่วมด้วย',stagePuppy:'ลูกสุนัข',stageKitten:'ลูกแมว',stageYoungAdult:'วัยโตตอนต้น',stageMatureAdult:'วัยโตเต็มวัย',stageSenior:'สูงวัย',contextPuppy:'ลูกสุนัขมีความต้องการพลังงานและสารอาหารแตกต่างจากสุนัขโต โดยควรพิจารณาอัตราการเจริญเติบโตและขนาดตัวเมื่อโตเต็มวัยร่วมด้วย',contextKitten:'ลูกแมวกำลังเจริญเติบโตและต้องการพลังงานกับสารอาหารที่เหมาะกับการเติบโต',contextYoungAdult:'ควรปรับปริมาณพลังงานเพื่อรักษารูปร่างและน้ำหนักตัวที่เหมาะสม และป้องกันภาวะน้ำหนักเกิน',contextMatureAdult:'ความต้องการพลังงานอาจเปลี่ยนไปตามอายุ ระดับกิจกรรม รูปร่าง และสุขภาพของสัตว์แต่ละตัว',contextSenior:'สัตว์สูงอายุไม่ควรถูกลดพลังงานโดยอัตโนมัติ ความต้องการพลังงานควรพิจารณารูปร่าง มวลกล้ามเนื้อ ระดับกิจกรรม สุขภาพ และการเปลี่ยนแปลงของแต่ละตัวร่วมด้วย',profileTitle:'บอกเราเรื่องเขาสักหน่อย',profileCopy:'ผลลัพธ์เป็นจุดเริ่มต้นสำหรับสัตว์เลี้ยงสุขภาพดี โปรดปรับตามน้ำหนักและสภาพร่างกายจริง',dog:'สุนัข',dogCaption:'Dog',cat:'แมว',catCaption:'Cat',petName:'ชื่อน้อง <i>ไม่บังคับ</i>',weight:'น้ำหนักปัจจุบัน',kg:'กก.',lifeStage:'ช่วงวัย',adult:'โตเต็มวัย (1–7 ปี)',young:'วัยอ่อน / กำลังโต',senior:'สูงวัย (7 ปีขึ้นไป)',
    neuteredQ:'ทำหมันแล้วหรือยัง?',neuteredYes:'ทำหมันแล้ว',neuteredNo:'ยังไม่ทำ',bcsTitle:'Body Condition Score (BCS)',estimatedBody:'ค่าประเมินรูปร่าง',mcsTitle:'Muscle Condition Score (MCS)',estimatedMuscle:'ค่าประเมินมวลกล้ามเนื้อ',howBCS:'วิธีประเมินรูปร่าง',howBCSCopy:'Body Condition Score ใช้ประเมินปริมาณไขมันในร่างกายจากทั้งการมองและการคลำ ควรคลำซี่โครงและสังเกตเอวกับรูปร่างหน้าท้อง ไม่ควรประเมินจากน้ำหนักตัวเพียงอย่างเดียว',howMCS:'วิธีประเมินมวลกล้ามเนื้อ',howMCSCopy:'Muscle Condition Score ใช้ประเมินมวลกล้ามเนื้อแยกจากปริมาณไขมัน โดยประเมินบริเวณศีรษะ หัวไหล่ แนวกระดูกสันหลัง และเชิงกราน',openWSAVA:'เปิดเอกสารต้นฉบับจาก WSAVA ↗',bcsCategories:{emaciated:'ผอมแห้งรุนแรง',veryThin:'ผอมมาก',thin:'ผอม',ideal:'เหมาะสม',overweight:'น้ำหนักเกิน',obese:'อ้วน',severelyObese:'อ้วนรุนแรง'},mcsLabels:{normal:'มวลกล้ามเนื้อปกติ',mild_loss:'สูญเสียเล็กน้อย',moderate_loss:'สูญเสียปานกลาง',severe_loss:'สูญเสียรุนแรง'},mcsDescriptions:{normal:'มวลกล้ามเนื้อบริเวณศีรษะ หัวไหล่ แนวกระดูกสันหลัง และเชิงกรานอยู่ในระดับปกติ ไม่พบการสูญเสียกล้ามเนื้อชัดเจน',mild_loss:'พบการลดลงของมวลกล้ามเนื้อเล็กน้อยบริเวณศีรษะ หัวไหล่ กระดูกสันหลัง หรือเชิงกราน',moderate_loss:'พบการสูญเสียกล้ามเนื้อชัดเจน ทำให้แนวกระดูกบริเวณศีรษะ กระดูกสันหลัง หัวไหล่ หรือเชิงกรานเด่นขึ้น',severe_loss:'พบการสูญเสียกล้ามเนื้ออย่างรุนแรง แนวกระดูกเด่นชัดมากและมีการลดลงของมวลกล้ามเนื้ออย่างมาก'},nutritionRiskTitle:'ข้อควรใส่ใจด้านโภชนาการ',riskBCSUnder:'BCS ต่ำกว่าช่วงที่เหมาะสม ควรติดตามน้ำหนักและปรึกษาสัตวแพทย์ก่อนวางแผนเพิ่มน้ำหนัก',riskBCSOver:'BCS สูงกว่าช่วงที่เหมาะสม ควรปรึกษาสัตวแพทย์เพื่อวางแผนควบคุมน้ำหนักอย่างเหมาะสม',riskMCSMild:'การสูญเสียกล้ามเนื้อเป็นปัจจัยเสี่ยงด้านโภชนาการ ควรติดตามน้ำหนัก ปริมาณอาหารที่กิน และมวลกล้ามเนื้ออย่างต่อเนื่อง',riskMCSVet:'การสูญเสียกล้ามเนื้อระดับปานกลางหรือรุนแรงอาจเกี่ยวข้องกับอายุที่เพิ่มขึ้น ภาวะโภชนาการไม่เหมาะสม หรือโรคที่ซ่อนอยู่ แนะนำให้ได้รับการประเมินโดยสัตวแพทย์',activityQ:'กิจกรรมในแต่ละวัน',low:'น้อย',lowDetail:'เดินเล่นหรือเล่นเบา ๆ ต่ำกว่า 30 นาที',moderate:'ปานกลาง',moderateDetail:'มีกิจกรรม 30–60 นาทีต่อวัน',high:'มาก',highDetail:'ออกกำลังหรือวิ่งเล่นมากกว่า 60 นาที',foodEnergy:'พลังงานของอาหารที่ใช้ <i>ดูจากฉลาก</i>',back:'ย้อนกลับ',reset:'คำนวณใหม่ ↻',
    resultHeading:'ปริมาณที่เหมาะกับน้อง',dailyEnergy:'พลังงานต่อวัน',dailyFood:'ปริมาณอาหารต่อวัน',twoMeals:'แบ่งเป็น 2 มื้อ',weekPrep:'เตรียมต่อสัปดาห์',treatEnergy:'พลังงานขนม',treatLimit:'ไม่เกิน 10%',note:'ตัวเลขนี้เป็นค่าเริ่มต้นจากน้ำหนัก ช่วงวัย การทำหมัน กิจกรรม และรูปร่างของน้อง ควรชั่งน้ำหนักและสังเกตสภาพร่างกายทุก 2–4 สัปดาห์',disclaimer:'สำหรับสัตว์เลี้ยงสุขภาพดีเท่านั้น หากกำลังตั้งท้อง ให้นม มีโรคประจำตัว หรือมีการเปลี่ยนแปลงน้ำหนักผิดปกติ โปรดปรึกษาสัตวแพทย์ก่อนปรับอาหาร',knowledgeTitle:'เริ่มให้ดี แล้วค่อยปรับให้พอดี',readLabel:'อ่านฉลาก',readLabelCopy:'กรอกค่า kcal ต่อ 100 กรัมจากอาหารที่น้องกินจริง เพื่อให้ผลลัพธ์แม่นยำขึ้น',weigh:'ชั่ง ไม่กะ',weighCopy:'ใช้เครื่องชั่งครัวตวงอาหารเป็นกรัม แทนการกะด้วยถ้วยหรือสายตา',follow:'ติดตามผล',followCopy:'ปรับปริมาณทีละน้อยตามน้ำหนัก รูปร่าง และกิจกรรมที่เปลี่ยนไป',footer:'เพื่อทุกมื้อที่พอดี',
    steps:['เลือกสัตว์เลี้ยง','ข้อมูลพื้นฐาน','รูปร่างและการทำหมัน','อาหารและกิจกรรม'],next:'ถัดไป <span>→</span>',view:'ดูคำแนะนำ <span>→</span>',resultFor:'ปริมาณที่เหมาะกับ',dogWord:'น้องหมา',catWord:'น้องแมว',intro:(weight,calories,stage)=>`คำนวณจากช่วงวัย ${stage} น้ำหนัก ${weight} กก. และอาหารที่ให้พลังงาน ${calories} kcal ต่อ 100 กรัม`,grams:'กรัม',perMeal:'กรัม / มื้อ'
  },
  en: {
    navHome:'Home',navReferences:'References',navCalc:'Calculator',heroEyebrow:'NUTRITION, SIMPLIFIED',heroTitle:'Just enough food<br /><em>for them.</em>',heroCopy:'A daily feeding guide for dogs and cats,<br class="desktop" /> based on the details that make them unique.',heroButton:'Start calculating <span>↓</span>',
    age:'Age',ageUnit:'Age unit',weeks:'Weeks',months:'Months',years:'Years',days:'Days',stepProgress:(step)=>`Step ${step} of 4`,adultSize:'Expected adult size',sizeAuto:'Estimate from current weight',sizeSmall:'Small — under 10 kg',sizeMedium:'Medium — 10–25 kg',sizeLarge:'Large — 25–40 kg',sizeGiant:'Giant — over 40 kg',sizeHelp:'When Auto is selected, Pawtion uses current weight as a practical estimate.',lifeStageTooltip:'Life stage helps Pawtion select an appropriate nutrition calculation pathway. Age alone does not determine energy needs; body condition, activity, reproductive status, growth, health, and individual variation also matter.',stagePuppy:'Puppy',stageKitten:'Kitten',stageYoungAdult:'Young Adult',stageMatureAdult:'Mature Adult',stageSenior:'Senior',contextPuppy:'Growing dogs have different energy and nutrient requirements from adult dogs. Growth rate and expected adult size should be considered.',contextKitten:'Growing kittens need energy and nutrients appropriate for healthy development.',contextYoungAdult:'Energy intake should be adjusted to maintain an ideal body condition and prevent excess weight gain.',contextMatureAdult:'Energy needs may gradually change with age, activity, body condition, and health status.',contextSenior:'Senior pets should not automatically receive fewer calories. Energy needs depend on body condition, muscle condition, activity, health, and individual changes associated with aging.',profileTitle:'Tell us a little about them.',profileCopy:'This result is a starting point for healthy pets. Adjust it based on real weight and body condition.',dog:'Dog',dogCaption:'Canine',cat:'Cat',catCaption:'Feline',petName:'Pet’s name <i>optional</i>',weight:'Current weight',kg:'kg',lifeStage:'Life stage',adult:'Adult (1–7 years)',young:'Young / growing',senior:'Senior (7+ years)',
    neuteredQ:'Has your pet been neutered?',neuteredYes:'Yes, neutered',neuteredNo:'Not neutered',bcsTitle:'Body Condition Score (BCS)',estimatedBody:'Estimated body condition',mcsTitle:'Muscle Condition Score (MCS)',estimatedMuscle:'Estimated muscle condition',howBCS:'How to assess body condition',howBCSCopy:'Body Condition Score estimates body fat using both visual appearance and palpation. Feel the ribs and observe the waist and abdominal contour rather than judging by body weight alone.',howMCS:'How to assess muscle condition',howMCSCopy:'Muscle Condition Score evaluates muscle mass separately from body fat. Check the muscles over the skull, shoulders, spine and pelvis.',openWSAVA:'Open the original WSAVA guide ↗',bcsCategories:{emaciated:'Emaciated',veryThin:'Very Thin',thin:'Thin',ideal:'Ideal',overweight:'Overweight',obese:'Obese',severelyObese:'Severely Obese'},mcsLabels:{normal:'Normal muscle mass',mild_loss:'Mild muscle loss',moderate_loss:'Moderate muscle loss',severe_loss:'Severe muscle loss'},mcsDescriptions:{normal:'Muscle mass appears normal over the skull, shoulders, spine and pelvis, with no obvious muscle wasting.',mild_loss:'A small reduction in muscle mass is noticeable over one or more areas such as the skull, shoulders, spine or pelvis.',moderate_loss:'Clear loss of muscle mass is present, with more prominent bony landmarks over the skull, spine, shoulders or pelvis.',severe_loss:'Marked muscle wasting is present, with very prominent bony landmarks and substantial loss of muscle tissue.'},nutritionRiskTitle:'Nutritional considerations',riskBCSUnder:'BCS is below the ideal range. Monitor weight and seek veterinary guidance before planning weight gain.',riskBCSOver:'BCS is above the ideal range. Seek veterinary guidance for an appropriate weight-management plan.',riskMCSMild:'Muscle loss is a nutritional risk factor. Consider monitoring body weight, food intake and muscle condition.',riskMCSVet:'Moderate or severe muscle loss may be associated with aging, inadequate nutrition or underlying disease. Veterinary evaluation is recommended.',activityQ:'Daily activity',low:'Low',lowDetail:'Light play or walks under 30 minutes',moderate:'Moderate',moderateDetail:'30–60 minutes of activity daily',high:'High',highDetail:'Exercise or play over 60 minutes',foodEnergy:'Food energy <i>from the label</i>',back:'Back',reset:'Calculate again ↻',
    resultHeading:'The right amount for them',dailyEnergy:'Daily energy',dailyFood:'Food per day',twoMeals:'Split into 2 meals',weekPrep:'Prepare per week',treatEnergy:'Treat energy',treatLimit:'Up to 10%',note:'This is a starting point based on weight, life stage, neuter status, activity and body condition. Weigh your pet and reassess their body condition every 2–4 weeks.',disclaimer:'For healthy pets only. Please consult a veterinarian before changing food for pregnant, nursing, ill pets, or those with unusual weight changes.',knowledgeTitle:'Start well. Then tailor it.',readLabel:'Read the label',readLabelCopy:'Enter the kcal per 100g from the food your pet actually eats for a more useful result.',weigh:'Weigh, don’t guess',weighCopy:'Use a kitchen scale to portion food in grams instead of estimating by eye.',follow:'Follow up',followCopy:'Fine-tune portions gradually as weight, body condition and activity change.',footer:'For every perfectly portioned meal.',
    steps:['Choose your pet','The basics','Body & neuter status','Food & activity'],next:'Next <span>→</span>',view:'See the guide <span>→</span>',resultFor:'The right amount for ',dogWord:'your dog',catWord:'your cat',intro:(weight,calories,stage)=>`Based on the ${stage} pathway, ${weight} kg and food with ${calories} kcal per 100g`,grams:'g',perMeal:'g / meal'
  }
};
const steps = [...document.querySelectorAll('.form-step')], next = document.querySelector('#next'), back = document.querySelector('#back'), progress = document.querySelector('.progress span');
function t(key){return dictionary[state.lang][key];}
function translatePage(){
  document.documentElement.lang = state.lang;
  document.querySelectorAll('[data-i18n]').forEach(el=>el.innerHTML=t(el.dataset.i18n));
  document.querySelectorAll('[data-i18n-html]').forEach(el=>el.innerHTML=t(el.dataset.i18nHtml));
  document.querySelectorAll('#language-toggle [data-language]').forEach(option=>option.classList.toggle('active',option.dataset.language===state.lang));
  document.querySelector('#language-toggle').setAttribute('aria-label',state.lang==='th'?'Switch to English':'เปลี่ยนเป็นภาษาไทย');
  document.querySelector('#pet-name').placeholder=state.lang==='th'?'เช่น โมจิ':'e.g. Mochi';
  document.querySelector('[data-species="dog"] img').alt=t('dog');
  document.querySelector('[data-species="cat"] img').alt=t('cat');
  renderLifeStage();
  renderAssessments();
  if(!document.querySelector('#result').hidden)renderNutritionalRisks();
  updateStep();
}
function updateStep(){
  steps.forEach(el=>el.classList.toggle('active',Number(el.dataset.step)===state.step));
  document.querySelector('#step-progress-text').textContent=t('stepProgress')(state.step);
  document.querySelector('#step-title').textContent=t('steps')[state.step-1];
  progress.style.width=`${state.step*25}%`;back.hidden=state.step===1;
  next.innerHTML=state.step===4?t('view'):t('next');
}
document.querySelector('#language-toggle').addEventListener('click',()=>{state.lang=state.lang==='th'?'en':'th';try{localStorage.setItem('pawtion-language',state.lang);}catch{}translatePage();});
const themeSelect=document.querySelector('#theme-select'),systemTheme=window.matchMedia('(prefers-color-scheme: light)');
function applyTheme(theme){
  if(!['light','dark','auto'].includes(theme))theme='auto';
  state.theme=theme;
  document.documentElement.dataset.theme=theme==='auto'?(systemTheme.matches?'light':'dark'):theme;
  document.documentElement.dataset.themeMode=theme;
  themeSelect.value=theme;
}
function getSavedTheme(){try{return localStorage.getItem('pawtion-theme')||'auto';}catch{return 'auto';}}
themeSelect.addEventListener('change',()=>{try{localStorage.setItem('pawtion-theme',themeSelect.value);}catch{}applyTheme(themeSelect.value);});
systemTheme.addEventListener('change',()=>{if(state.theme==='auto')applyTheme('auto');});
const ageYears=document.querySelector('#age-years'),ageMonthsInput=document.querySelector('#age-months'),ageDays=document.querySelector('#age-days'),adultSizeSelect=document.querySelector('#adult-size'),dogSizeField=document.querySelector('#dog-size-field');
function getLifeStageData(){const ageMonths=PawtionLifeStage.normalizeAgePartsToMonths(ageYears.value,ageMonthsInput.value,ageDays.value);const selectedSize=adultSizeSelect.value;const adultSize=selectedSize==='auto'?PawtionLifeStage.inferDogAdultSize(document.querySelector('#weight').value):selectedSize;const stage=ageMonths===null?null:PawtionLifeStage.classifyLifeStage(state.species,ageMonths,adultSize);return{ageMonths,adultSize,stage,sizeEstimated:selectedSize==='auto'};}
function getLifeStageRange(data){
  if(state.species==='cat'){const ranges={kitten:['แรกเกิดถึงอายุต่ำกว่า 1 ปี','Birth to under 1 year'],youngAdult:['อายุ 1 ปีถึงต่ำกว่า 7 ปี','Age 1 to under 7 years'],matureAdult:['อายุ 7–10 ปี','Age 7–10 years'],senior:['อายุมากกว่า 10 ปี','Over 10 years']};return ranges[data.stage][state.lang==='th'?0:1];}
  const c=PawtionLifeStage.DOG_LIFE_STAGE_CONFIG,size=data.adultSize,puppy=c.puppyEndMonths[size],maturity=c.maturityMonths[size]/12,senior=c.seniorStartMonths[size]/12;
  const ranges={puppy:[`แรกเกิดถึงอายุต่ำกว่า ${puppy} เดือน (ประเมินตามขนาดเมื่อโตเต็มวัย)`,`Birth to under ${puppy} months (estimated by adult size)`],youngAdult:[`${puppy} เดือนถึงต่ำกว่า ${maturity} ปี`,`${puppy} months to under ${maturity} years`],matureAdult:[`${maturity} ปีถึงต่ำกว่า ${senior} ปี`,`${maturity} to under ${senior} years`],senior:[`${senior} ปีขึ้นไป (ค่าประมาณตามขนาดตัว)`,`${senior}+ years (size-based estimate)`]};return ranges[data.stage][state.lang==='th'?0:1];
}
function renderLifeStage(){const data=getLifeStageData(),range=document.querySelector('#life-stage-range');dogSizeField.hidden=state.species!=='dog';if(!data.stage){document.querySelector('#life-stage-value').textContent='—';range.textContent='';document.querySelector('#life-stage-context').textContent='';return;}const key={puppy:'Puppy',kitten:'Kitten',youngAdult:'YoungAdult',matureAdult:'MatureAdult',senior:'Senior'}[data.stage];document.querySelector('#life-stage-value').textContent=t(`stage${key}`);range.textContent=getLifeStageRange(data);document.querySelector('#life-stage-context').textContent=t(`context${key}`);}
[ageYears,ageMonthsInput,ageDays,adultSizeSelect,document.querySelector('#weight')].forEach(input=>input.addEventListener('input',renderLifeStage));
document.querySelector('#life-stage-info').addEventListener('click',event=>{const tip=document.querySelector('#life-stage-tooltip'),open=tip.hidden;tip.hidden=!open;event.currentTarget.setAttribute('aria-expanded',String(open));});
document.querySelectorAll('[data-species]').forEach(button=>button.addEventListener('click',()=>{state.species=button.dataset.species;document.querySelectorAll('[data-species]').forEach(item=>item.classList.toggle('selected',item===button));renderLifeStage();renderAssessments();}));
document.querySelectorAll('[data-neutered]').forEach(button=>button.addEventListener('click',()=>{state.neutered=button.dataset.neutered;document.querySelectorAll('[data-neutered]').forEach(item=>item.classList.toggle('selected',item===button));}));
const bcsSlider=document.querySelector('#bcs-slider'),mcsSelector=document.querySelector('#mcs-selector');
bcsSlider.addEventListener('input',()=>{state.bcs=Number(bcsSlider.value);renderAssessments();});
PawtionBodyCondition.MCS_VALUES.forEach(value=>{const button=document.createElement('button');button.type='button';button.dataset.mcs=value;button.addEventListener('click',()=>{state.mcs=value;renderAssessments();});mcsSelector.append(button);});
function renderAssessments(){
  if(!bcsSlider)return;
  bcsSlider.value=String(state.bcs);bcsSlider.style.setProperty('--bcs-progress',`${((state.bcs-1)/8)*100}%`);
  const category=PawtionBodyCondition.getBCSCategory(state.bcs);document.querySelector('#bcs-category').textContent=t('bcsCategories')[category];document.querySelector('#bcs-score').textContent=`${state.bcs}/9`;document.querySelector('#bcs-description').textContent=PawtionBodyCondition.getBCSDescription(state.bcs,state.species,state.lang);
  const exampleScore=state.bcs<=2?1:state.bcs<=4?3:state.bcs===5?5:state.bcs<=7?7:9,exampleImage=document.querySelector('#bcs-example-image'),exampleLabel=document.querySelector('#bcs-example-label');exampleImage.src=`assets/wsava-guides/bcs-examples/bcs-${state.species}-${exampleScore}.jpg`;exampleImage.alt=state.lang==='th'?`ตัวอย่างรูปร่างจาก WSAVA ช่วง BCS ${exampleScore}/9 สำหรับ${state.species==='dog'?'สุนัข':'แมว'}`:`WSAVA body-condition example for ${state.species==='dog'?'dogs':'cats'}, BCS ${exampleScore}/9`;exampleLabel.textContent=state.lang==='th'?`ตัวอย่าง WSAVA · BCS ${exampleScore}/9`:`WSAVA example · BCS ${exampleScore}/9`;
  mcsSelector.querySelectorAll('button').forEach(button=>{button.textContent=t('mcsLabels')[button.dataset.mcs];button.classList.toggle('selected',button.dataset.mcs===state.mcs);});document.querySelector('#mcs-description').textContent=t('mcsDescriptions')[state.mcs];
  document.querySelectorAll('[data-bcs-guide]').forEach(image=>{image.hidden=image.dataset.bcsGuide!==state.species;image.alt=state.lang==='th'?`แผนภาพ Body Condition Score สำหรับ${state.species==='dog'?'สุนัข':'แมว'}จาก WSAVA`:`WSAVA Body Condition Score chart for ${state.species==='dog'?'dogs':'cats'}`;});
  document.querySelectorAll('[data-mcs-guide]').forEach(image=>{image.hidden=image.dataset.mcsGuide!==state.species;image.alt=state.lang==='th'?`แผนภาพ Muscle Condition Score สำหรับ${state.species==='dog'?'สุนัข':'แมว'}จาก WSAVA`:`WSAVA Muscle Condition Score chart for ${state.species==='dog'?'dogs':'cats'}`;});
  const cat=state.species==='cat';document.querySelector('#bcs-guide-source').href=cat?'https://wsava.org/wp-content/uploads/2025/06/WSAVA_BCSCat_BCSCat_Nutrition_250612.pdf':'https://wsava.org/wp-content/uploads/2025/06/WSAVA_BCSCat_BCSDog_Nutrition_250612.pdf';document.querySelector('#mcs-guide-source').href=cat?'https://wsava.org/wp-content/uploads/2020/01/Muscle-Condition-Score-Chart-for-Cats.pdf':'https://wsava.org/wp-content/uploads/2020/01/Muscle-Condition-Score-Chart-for-Dogs.pdf';
}
document.querySelectorAll('.activity-list label').forEach(label=>label.addEventListener('click',()=>document.querySelectorAll('.activity-list label').forEach(item=>item.classList.toggle('selected',item===label))));
function valid(){if(state.step!==2&&state.step!==4)return true;const invalid=[...steps[state.step-1].querySelectorAll('[required]')].find(input=>!input.value||!input.checkValidity());if(invalid){invalid.reportValidity();return false;}return true;}
next.addEventListener('click',()=>{if(!valid())return;if(state.step<4){state.step++;updateStep();}else showResult();});back.addEventListener('click',()=>{state.step--;updateStep();});
function showResult(){
  const weight=Number(document.querySelector('#weight').value), caloriesPer100g=Number(document.querySelector('#food-calories').value), activity=document.querySelector('input[name="activity"]:checked').value,name=document.querySelector('#pet-name').value.trim(),lifeStage=getLifeStageData();
  const factor=PawtionNutrition.getEnergyFactor({species:state.species,stage:lifeStage.stage,ageMonths:lifeStage.ageMonths,neutered:state.neutered,activity,bcs:state.bcs,mcs:state.mcs}),{kcal}=PawtionNutrition.calculateEnergy(weight,factor);
  const grams=Math.round(kcal/caloriesPer100g*100),pet=t(state.species==='dog'?'dogWord':'catWord');
  document.querySelector('#result-heading').textContent=name?`${t('resultFor')}${name}`:`${t('resultFor')}${pet}`;
  const stageName=document.querySelector('#life-stage-value').textContent;document.querySelector('#result-intro').textContent=t('intro')(weight,caloriesPer100g,stageName);
  document.querySelector('#calorie-result').innerHTML=`${kcal.toLocaleString()} <small>kcal</small>`;
  document.querySelector('#gram-result').innerHTML=`${grams.toLocaleString()} <small>${t('grams')}</small>`;
  document.querySelector('#meal-result').textContent=`${Math.round(grams/2)} ${t('perMeal')}`;
  document.querySelector('#week-result').textContent=`${(grams*7).toLocaleString()} ${t('grams')}`;
  renderNutritionalRisks();
  document.querySelector('#result').hidden=false;document.querySelector('#result').scrollIntoView({behavior:'smooth',block:'start'});
}
function renderNutritionalRisks(){const flags=PawtionBodyCondition.getNutritionalRiskFlags(state),box=document.querySelector('#nutrition-risk'),messages=document.querySelector('#nutrition-risk-messages');messages.replaceChildren();const keys=[];if(flags.includes('bcs_under'))keys.push('riskBCSUnder');if(flags.includes('bcs_over'))keys.push('riskBCSOver');if(flags.includes('mcs_mild'))keys.push('riskMCSMild');if(flags.includes('mcs_moderate')||flags.includes('mcs_severe'))keys.push('riskMCSVet');keys.forEach(key=>{const p=document.createElement('p');p.textContent=t(key);messages.append(p);});box.hidden=!keys.length;}
document.querySelector('#reset').addEventListener('click',()=>{document.querySelector('#result').hidden=true;document.querySelector('#calculator').scrollIntoView({behavior:'smooth'});});
const pageLinks=[...document.querySelectorAll('.primary-nav [data-page]')];
function updateActiveNavigation(){const calculator=document.querySelector('#calculator');const active=window.scrollY>=calculator.offsetTop-180?'calculator':'home';pageLinks.forEach(link=>{const selected=link.dataset.page===active;link.classList.toggle('active',selected);if(selected)link.setAttribute('aria-current','page');else link.removeAttribute('aria-current');});}
window.addEventListener('scroll',updateActiveNavigation,{passive:true});
window.addEventListener('hashchange',()=>requestAnimationFrame(updateActiveNavigation));
applyTheme(getSavedTheme());
translatePage();
updateActiveNavigation();
